# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-12-30 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=200)),
                ('designation', models.TextField(blank=True)),
                ('Description', models.TextField(blank=True)),
                ('Experience', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('Education', models.TextField(blank=True)),
                ('Experience', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('Projects', models.TextField(blank=True)),
            ],
        ),
    ]
