# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-13 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20181231_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_company',
            field=models.TextField(blank=True),
        ),
    ]
