# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-17 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_profile_current_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Job_Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Profile')),
            ],
        ),
    ]
